server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:h2:file:./db/gps_test
  flyway:
    locations: classpath:/db/migration
  web:
    resources:
      static-locations: classpath:/static/files
  mvc:
    static-path-pattern: /content/**
gps:
  uploadDir: ./static/files